Airlines.WebUI/Controllers/PlanesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Airlines.Data.Concrete.EfCore;
using Airlines.Entity;
using Airlines.Data.Abstract;
using Airlines.WebUI.Models;
using System.Diagnostics;

namespace Airlines.WebUI.Controllers
{
    public class PlanesController : Controller
    {
        private IPlaneRepository planeRepository;

        public PlanesController(IPlaneRepository _planeRepository)
        {
            planeRepository = _planeRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PlaneList()
        {
            return View(planeRepository.GetAll());
        }

        [HttpGet]
        public IActionResult PlaneCreate()
        {
            return View();
        }

        [HttpPost]
        public IActionResult PlaneCreate(Plane entity)
        {
            if (ModelState.IsValid)
            {
                planeRepository.AddPlane(entity);
                return RedirectToAction("PlaneList");
            }

            return View(entity);
        }

        [HttpGet]
        public IActionResult PlaneEdit(int id)
        {
            return View(planeRepository.GetById(id));
        }

        [HttpPost]
        public IActionResult PlaneEdit(Plane entity)
        {
            if (ModelState.IsValid)
            {
                planeRepository.UpdatePlane(entity);
                TempData["message"] = $"Id : {entity.PlaneId} İsimli : {entity.PlaneName} Tipli : {entity.PlaneType} Uçak Bilgileri Güncellendi";
                return RedirectToAction("PlaneList");
            }

            return View(entity);
        }

        [HttpGet]
        public IActionResult PlaneDelete(int id)
        {
            return View(planeRepository.GetById(id));
        }

        [HttpPost, ActionName("PlaneDelete")]
        public IActionResult PlaneDeleteConfirmed(int PlaneId)
        {
            planeRepository.DeletePlane(PlaneId);
            TempData["message"] = $"{PlaneId} Numaralı Kullanıcı Silindi.";
            return RedirectToAction("PlaneList");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Airlines.WebUI/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Airlines.Data.Concrete.EfCore;
using Airlines.Entity;
using Airlines.Data.Abstract;
using Airlines.WebUI.Models;
using System.Diagnostics;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore.Storage;

namespace Airlines.WebUI.Controllers
{

    public class UsersController : Controller
    {
        private IUserRepository userRepository;

        public UsersController(IUserRepository repository)
        {
            userRepository = repository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult UserLogin(string UserEmail, string UserPassword)
        {
            if (!string.IsNullOrEmpty(UserEmail) && string.IsNullOrEmpty(UserPassword))
            {
                return RedirectToAction("Index", "Home");
            }
            ClaimsIdentity identity = null;
            bool isAuthenticated = false;

            var userControl = userRepository.GetByLogin(UserEmail,UserPassword);

            if (userControl != null)
            {
                identity = new ClaimsIdentity(new[] {
                    new Claim(ClaimTypes.Name, UserEmail),
                    new Claim(ClaimTypes.Role, userControl.UserAuthority),
                }, CookieAuthenticationDefaults.AuthenticationScheme);

                isAuthenticated = true;
            }
            else
            {
                TempData["message"] = "Böyle bir kullanıcı bulunmuyor. Lütfen tekrar deneyiniz.";
                return RedirectToAction("Index", "Home");
            }
            if (isAuthenticated)
            {
                var principal = new ClaimsPrincipal(identity);

                var login = HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                return RedirectToAction("AirlineList", "Home");
            }

            return View();
        }

        public IActionResult UserLogout()
        {
            var login = HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult UserList()
        {
            //ViewData["UserName"] = new SelectList(userRepository.GetAll(), "UserId", "UserName");
            return View(userRepository.GetAll());
        }

        [HttpGet]
        public IActionResult UserCreate()
        {
            //ViewBag.Airlines = new SelectList(airlineRepository.GetAll(), "AirlineId", "AirlineNumber").Count()+1;

            return View();
        }

        [HttpPost]
        public IActionResult UserCreate(User entity)
        {
            if (ModelState.IsValid)
            {
                userRepository.AddUser(entity);
                return RedirectToAction("UserList");
            }

            return View(entity);
        }

        [HttpGet]
        public IActionResult UserEdit(int id)
        {
            return View(userRepository.GetById(id));
        }

        [HttpPost]
        public IActionResult UserEdit(User entity)
        {
            if (ModelState.IsValid)
            {
                userRepository.UpdateUser(entity);
                TempData["message"] = $"Id : {entity.UserId} İsimli : {entity.UserName} E-Postalı : {entity.UserEmail} Kullanıcı Bilgileri Güncellendi";
                return RedirectToAction("UserList");
            }

            return View(entity);
        }

        [HttpGet]
        public IActionResult UserDelete(int id)
        {
            return View(userRepository.GetById(id));
        }

        [HttpPost, ActionName("UserDelete")]
        public IActionResult UserDeleteConfirmed(int UserId)
        {
            userRepository.DeleteUser(UserId);
            TempData["message"] = $"{UserId} Numaralı Kullanıcı Silindi.";
            return RedirectToAction("UserList");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Airlines.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - Airlines AnaSayfa</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
</head>

<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" asp-controller="Home" asp-action="AirlineList">Airlines Admin</a><button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button><!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <!-- Navbar-->
        <font color="white">
        @User.Identity.Name
        </font>
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Settings</a><a class="dropdown-item" href="#">Activity Log</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" asp-controller="Users" asp-action="UserLogout">Çıkış Yap</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Uçuş İşlemleri</div>
                        <a class="nav-link" asp-controller="Home" asp-action="AirlineList">
                            <div class="sb-nav-link-icon"><i class="fas fa-calendar-alt"></i></div>
                            Tüm Uçuşlar
                        </a>
                        <a class="nav-link" asp-controller="Home" asp-action="AirlineCreate">
                            <div class="sb-nav-link-icon"><i class="fas fa-calendar-plus"></i></div>
                            Uçuş Ekle
                        </a>
                        @if (@User.IsInRole("Admin"))
                        {
                        <div class="sb-sidenav-menu-heading">Kullanıcı İşlemleri</div>
                        <a class="nav-link" asp-controller="Users" asp-action="UserList">
                            <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
                            Tüm Kullanıcılar
                        </a>
                        <a class="nav-link" asp-controller="Users" asp-action="UserCreate">
                            <div class="sb-nav-link-icon"><i class="fas fa-user-plus"></i></div>
                            Kullanıcı Ekle
                        </a>
                        }
                        <div class="sb-sidenav-menu-heading">Uçak İşlemleri</div>
                        <a class="nav-link" asp-controller="Planes" asp-action="PlaneList">
                            <div class="sb-nav-link-icon"><i class="fas fa-plane"></i></div>
                            Tüm Uçaklar
                        </a>
                        <a class="nav-link" asp-controller="Planes" asp-action="PlaneCreate">
                            <div class="sb-nav-link-icon"><i class="fas fa-plane-departure"></i></div>
                            Uçak Ekle
                        </a>
                        <!--
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="layout-static.html">Static Navigation</a><a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a></nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Pages
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Authentication
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="login.html">Login</a><a class="nav-link" href="register.html">Register</a><a class="nav-link" href="password.html">Forgot Password</a></nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Error
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="401.html">401 Page</a><a class="nav-link" href="404.html">404 Page</a><a class="nav-link" href="500.html">500 Page</a></nav>
                                </div>
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">Addons</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Charts
                        </a><a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Tables
                        </a>-->
                    </div>
                         
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Airlines Admin
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            @if (TempData["message"] != null)
            {
                <main>
                    <div class="container-fluid">
                        <div class="alert alert-success">
                            @TempData["message"]
                        </div>
                    </div>
                </main>
                        }
            @RenderBody()
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Airlines Admin 2020</div>
                        <div>
                            <a href="#">Gizlilik Politikası</a>
                            &middot;
                            <a href="#">Şartlar &amp; Koşullar</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
</div>


    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/scripts.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="~/js/datatables-demo.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/js/chart-area-demo.js"></script>
    <script src="~/js/chart-bar-demo.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>